export type M3ColorRole = 
    'primary'|
    'surface-tint'|
    'on-primary'|
    'primary-container'|
    'on-primary-container'|
    'secondary'|
    'on-secondary'|
    'secondary-container'|
    'on-secondary-container'|
    'tertiary'|
    'on-tertiary'|
    'tertiary-container'|
    'on-tertiary-container'|
    'error'|
    'on-error'|
    'error-container'|
    'on-error-container'|
    'background'|
    'on-background'|
    'surface-variant'|
    'on-surface-variant'|
    'outline'|
    'outline-variant'|
    'shadow'|
    'scrim'|
    'inverse-surface'|
    'inverse-on-surface'|
    'inverse-primary'|
    'primary-fixed'|
    'on-primary-fixed'|
    'primary-fixed-dim'|
    'on-primary-fixed-variant'|
    'secondary-fixed'|
    'on-secondary-fixed'|
    'secondary-fixed-dim'|
    'on-secondary-fixed-variant'|
    'tertiary-fixed'|
    'on-tertiary-fixed'|
    'tertiary-fixed-dim'|
    'on-tertiary-fixed-variant'|
    'surface'|
    'on-surface'|
    'surface-dim'|
    'surface-bright'|
    'surface-container-lowest'|
    'surface-container-low'|
    'surface-container'|
    'surface-container-high'|
    'surface-container-highest'